{
    stores: allStores {
        nodes {
            id
            name
      		company: companyByCompanyId {
                category: companyCategoryByCompanyCategoryId {
                    key
                }
            }
            address: addressByAddressId {
                lat,
                lng
            }
        }
    }
}
